### PR TITLE
Modify More demo links and title

### LINKED ISSUE #114: Landing page has link for Plone 6 in More demo sites for you section
**Describe the bug**
The landing page (demo page) has a section for more demo sites which contains a self redirecting link to Plone 6 itself. Which can be removed as this is the landing page for Plone 6 demo itself.

**To Reproduce**

1. Go to https://demo.plone.org/
3. Scroll down to More demo sites for you Section
3. 2. Click on Plone 6 
4. It won't redirect anywhere because this is the demo page for Plone 6 itself

**Expected behavior**
The Plone 6 redirecting link should be removed from that section as its not a different demo page

### PR DESCRIPTION
**Pull request by PriyanshuRj**
resolves #114 
Modifed anchor text of Plone 6 to Plone 6 (this site) and changed the redirecting link for Plone 6 Classic UI

### CODE REVIEW

**Comment by stevepiercy** [comment]
@PriyanshuRj see https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request for guidance on the required news item.

**Comment by stevepiercy** [comment]
Should this PR include a link to the Plone 5.2 demo?

https://52.demo.plone.org/

**Comment by PriyanshuRj** [comment]
> Should this PR include a link to the Plone 5.2 demo?
> 
> https://52.demo.plone.org/

Should I include this ?

**Review by davisagli — APPROVED** [review]
Thanks, this looks good to me.

I am not sure if we should add a link to the Plone 5.2 demo. I think probably not, since it is old and not the right thing to highlight for people who are new to Plone. But I am okay with adding it if someone has a good reason.

**Pull request merged**
