### PR TITLE
Do not set the nonfolderish_tabs registry to False

### LINKED ISSUE #145: Type Links does not appear in the Volto menu
This is because the `nonfolderish_tabs` setting is set to False:

https://github.com/plone/plone.volto/blob/b997f4b2e8abf03a8e9ac31e8342ddc3e612a123/src/plone/volto/profiles/default/registry.xml#L3-L7

And the navigation service checks this configuration:

https://github.com/plone/plone.restapi/blob/3ad0f0534b49c9cb7ccde4d568a627d2f8e420ec/src/plone/restapi/services/navigation/get.py#L116-L117

As the Link is not folderish, it does not appear in the menu when this setting is False.

This configuration was made in this commit by @sneridagh: https://github.com/plone/plone.volto/commit/6b9426dbbe91962ca372d2b6de020bd5e87bbdc7

Why was this configuration made? How does it influence Volto? Can we leave the default value True, so that the Link type appears in the menu?

### PR DESCRIPTION
**Pull request by wesleybl**
The default setting of `True` will be set. With this, the content types in `displayed_types`  will appear in the menu, regardless of whether they are folderish. This mainly favored the Link type, which was not appearing in the menu because it was not folderish.

fixes #145

### CODE REVIEW

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@wesleybl I would leave out the upgrade step. It's okay to change the value of the setting for new sites, but we shouldn't change it for existing sites where it might have been set intentionally.

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
> I would leave out the upgrade step

@davisagli done.

**Review by davisagli — COMMENTED** [review]
Any concern about this, @sneridagh?

**Comment by wesleybl** [comment]
@sneridagh can you take a look here please?

**Review by davisagli — APPROVED** [review]

**Pull request merged**
