### PR TITLE
Use plone/code-analysis-action and plone/code-quality

### PR DESCRIPTION
**Pull request by ericof**

### CODE REVIEW

**Comment by ericof** [comment]
Closes #68

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — COMMENTED** [review]
Basically makes sense to me.

Do I understand correctly that one has to run "make lint" once manually in order to install the git hooks? Should that be mentioned in the readme or contributor docs?

Can the flakeheaven configuration in pyproject.toml be removed?

**Comment by mauritsvanrees** [comment]
> Basically makes sense to me.

For me too, mostly. After all these years I am still not into docker. I had to (re)install it today. I must say it is much faster than I feared: calling a local black or a black in a docker does not seem to matter much, if you ignore the first run.

One doubt I have, is the following:
If I see it correctly, `make lint` is called both on GitHub Actions and in the pre-commit hook, and this uses docker. This is good.
But if you want to *apply* for example black, you call `make black` and this still runs a locally installed `bin/black`. It uses the [`requirements.txt`](https://github.com/plone/code-quality/blob/main/requirements.txt) from the `code-quality` image, so it should be the same version. But wouldn't it be better to call the `black` command that is installed in docker?

Further, the yaml file is a bit repetitive and therefore long. But that could be simplified later, if the current setup works and is used by more packages.

> Do I understand correctly that one has to run "make lint" once manually in order to install the git hooks? Should that be mentioned in the readme or contributor docs?

Yes please.

> Can the flakeheaven configuration in pyproject.toml be removed?

No, it cannot. The docker image still makes use of it. Just try: run `make lint` and all it well. Remove `pyproject.toml` and run the command again and you will have lots of errors. `pyproject.toml` has a few settings for `pycodestyle` to ignore some errors and warnings that are irrelevant.

**Comment by ericof** [comment]
@mauritsvanrees The reason to install the packages locally is to avoid permission issues with the formatter (As, by default, Docker mounts the host folder as root).

**Review by davisagli — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
@ericof What I mean is doing this in the Makefile:

```
FORMAT=docker run --rm -v "$(PWD)":/github/workspace plone/code-quality:${CODE_QUALITY_VERSION} format

.PHONY: format
format: ## Format the codebase according to our standards
	$(FORMAT) "$(CHECK_PATH)"
```

Then `make format` calls the `format` command from docker, and this runs black, isort and zpretty, without needing to install these packages locally. Works when I try it.

The only problem currently is that `format` does not accept as much parameters as `check`, so you cannot run individual commands, like only black, no isort/zpretty. Otherwise, this works fine.

**Pull request merged**
