### PR TITLE
Modify Plone 6 in More demo sites for you

### LINKED ISSUE #114: Landing page has link for Plone 6 in More demo sites for you section
**Describe the bug**
The landing page (demo page) has a section for more demo sites which contains a self redirecting link to Plone 6 itself. Which can be removed as this is the landing page for Plone 6 demo itself.

**To Reproduce**

1. Go to https://demo.plone.org/
3. Scroll down to More demo sites for you Section
3. 2. Click on Plone 6 
4. It won't redirect anywhere because this is the demo page for Plone 6 itself

**Expected behavior**
The Plone 6 redirecting link should be removed from that section as its not a different demo page

### PR DESCRIPTION
**Pull request by PriyanshuRj**
resolves #114 
Modifed anchor text of Plone 6 to Plone 6 (this site) and changed the redirecting link for Plone 6 Classic UI

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
I approve, but:

- A core contributor should also review.
- You must sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement) before this can be merged.

**Comment by PriyanshuRj** [comment]
> * must

Okey thanks I just got added to the "Developer" team of plone

**Comment by PriyanshuRj** [comment]
> I approve, but:
> 
>     * A core contributor should also review.
> 
>     * You must sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement) before this can be merged.

Okey I just became a part of the "Developer" team of Plone Organization.

**Comment by stevepiercy** [comment]
- Please open a PR in this repo, not from your fork.
- Include a news item. Use https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request as a guide.

**Pull request closed without merging**
