### PR TITLE
No draftjs in default homepages

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jensens @mauritsvanrees it seems Jenkins is broken... I started the build several times and breaks when the buildout bootstraps.

**Comment by jensens** [comment]
> @jensens @mauritsvanrees it seems Jenkins is broken... I started the build several times and breaks when the buildout bootstraps.

cc @plone/ai-team

**Comment by fredvd** [comment]
It seems coredev wants to check out a non existing docs branch by mr.developer.

There are a lot of warnings about invalid package numbers affer that, but maybe the mr.developer error is enough for an error return status so that the runner breaks/exits with a failure? 

@jensens @mauritsvanrees :

Please be aware there is no longer a testing team with people dedicated to supporting the testing setup and analysiing build failures.  Gil and me try to keep jenkins the service running and configured from the ai-team when we took over that part of the responsabity from the testing team, but the ai-team cannot take over everything the testing team once did. 

‘’’
mr.developer: Cloned 'docs-volto' with git using branch 'volto-frontend' from 'https://github.com/plone/documentation.git'.
mr.developer: git cloning of 'docs-volto' failed.
mr.developer: warning: Could not find remote branch volto-frontend to clone.
mr.developer: fatal: Remote branch volto-frontend not found in upstream origin
mr.developer: 
mr.developer: Cloned 'docs-backend' with git using branch 'backend-6' from 'https://github.com/plone/documentation.git'.
mr.developer: Cloned 'docs-classicui' with git using branch 'classic-ui' from 'https://github.com/plone/documentation.git'.
mr.developer: Cloned 'Zope' with git using branch 'master' from 'https://github.com/zopefoundation/Zope.git'.
mr.developer: Cloned 'plone.app.layout' with git using branch 'master' from 'https://github.com/plone/plone.app.layout.git'.
mr.developer: There have been errors, see messages above.
/home/jenkins/shiningpanda/jobs/69a88cbb/virtualenvs/0dd3bfc1/lib/python3.7/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
/home/jenkins/shiningpanda/jobs/69a88cbb/virtualenvs/0dd3bfc1/lib/python3.7/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: list-0.5.0 is an invalid version
‘’’

**Comment by stevepiercy** [comment]
I deleted the branch `volto-frontend` from `plone/documentation` because it had nothing useful on it, and we are now using the branch `6-dev` as the only primary branch for the development and imminent release of Plone 6 Documentation.

Apologies for the negative impact. How can I correct the issue so that that branch, as well as the other two obsolete branches, are not checked out and that the new `6-dev` branch is checked out? I am not familiar with this environment.

**Comment by jensens** [comment]
I corrected buildout.coredev to only use the 6-dev in its sources.cfg 
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
Also these two branches are obsolete and were merged into `6-dev` on documentation.

```
mr.developer: Cloned 'docs-backend' with git using branch 'backend-6' from 'https://github.com/plone/documentation.git'.
mr.developer: Cloned 'docs-classicui' with git using branch 'classic-ui' from
```

How do I add `6-dev` to the checkout?

**Comment by stevepiercy** [comment]
I made this PR yesterday https://github.com/plone/buildout.coredev/pull/766

**Comment by jensens** [comment]
> I made this PR yesterday [plone/buildout.coredev#766](https://github.com/plone/buildout.coredev/pull/766)

Ah, sorry, I did not check before.

**Comment by sneridagh** [comment]
Yay! Green! :)

**Pull request merged**
