### PR TITLE
Fix deprecated imports

### PR DESCRIPTION
**Pull request by petschki**
While working on other deprecation fixes I wanted to do this here too, but now I see that `main` branch is tested against Plone 5.2 also ... thought I read in the CHANGELOG that 4.x is Plone 6 only?

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@petschki thanks for taking care of this. As far as I am concerned plone.volto should be compatible with both Plone 5.2 and 6.x for the time being and be in sync with our release policy for plone.restapi. We have certain features in both plone.restapi and plone.volto that work for Plone 6 only. Though, those are conditional imports so we support a feature if we have Plone 6.

@sneridagh @mauritsvanrees opinions?

**Comment by sneridagh** [comment]
I suscribe to all that @tisto said.

@petschki the comment in CHANGELOG refers to an optional behavior (and I don't know why @robgietema stated that it was Plone 6 only). Since tests are passing in 5.2 I assume the package goes well in there.

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
