### PR TITLE
Corrected some minor spelling issues in Volto Demo Homepage

### PR DESCRIPTION
**Pull request by rohnsha0**
corrected "easily" spelling as asked for in ISSUE #65

### CODE REVIEW

**Comment by stevepiercy** [comment]
@rohnsha0 please include a change log entry using towncrier, as described in this Community Forum post:

https://community.plone.org/t/using-towncrier-for-changes-rst-in-plone-packages/6486/14

**Review by stevepiercy — APPROVED** [review]
LGTM. Needs a change log entry via towncrier and pass on Jenkins before merging.

**Review by mauritsvanrees — APPROVED** [review]
Thanks.

For such a small change, a change log entry is not needed in my view. Jenkins has one failure, but it is unrelated. I will merge.

**Comment by rohnsha0** [comment]
@stevepiercy @mauritsvanrees but i don't know how to add any log entries!
How do I do one.... For any of my future contributions!

**Comment by stevepiercy** [comment]
@rohnsha0 almost all Plone repos have CI/CD. These jobs run whenever you create a pull request or push additional commits to an open PR. Usually one of the checks is for a change log entry in a specified format, as in this example's friendly reminder:

Screen Shot 2022-08-12 at 10 05 38 PM

And the link [Details](https://jenkins.plone.org/roboto/missing-changelog) has... well... details.

Some repositories use towncrier, as described in this Community Forum post and in that Details link:

https://community.plone.org/t/using-towncrier-for-changes-rst-in-plone-packages/6486/14

Others have a `CHANGES.md|rst|txt` file.

**Comment by mauritsvanrees** [comment]
If you look at the [raw `CHANGES.rst`](https://raw.githubusercontent.com/plone/plone.volto/main/CHANGES.rst), there is a link to https://github.com/plone/plone.releaser/blob/master/ADD-A-NEWS-ITEM.rst explaining it too.

**Comment by rohnsha0** [comment]
@stevepiercy @mauritsvanrees Haha! Got it! Thanks for the explainations! :)

**Pull request merged**
