### PR TITLE
Add missing method in scaling customization

### PR DESCRIPTION
**Pull request by cekk**
In classic Plone the scaling factory breaks without this method

### CODE REVIEW

**Comment by cekk** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@cekk do you have a pointer to a bug report or something? I just would like to understand what goes wrong.

**Comment by mauritsvanrees** [comment]
> @cekk do you have a pointer to a bug report or something? I just would like to understand what goes wrong.

The [`IImageScaleFactory` interface](https://github.com/plone/plone.scale/blob/08f276f75fd9bbf3a84a1aa896918902556c3ef5/plone/scale/interfaces.py#L59) requires it.
Both `plone.scale` and `plone.namedfile` call it when creating or pre-creating a scale, so it would quickly fail with the old implementation.

**Review by mauritsvanrees — APPROVED** [review]
This works.

But I would like to suggest to inherit from [`DefaultImageScalingFactory`](https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/scaling.py#L213) instead. The current implementation, especially the `__call__` method, is copied from there, and might be missing fixes. If Plone 5.2 still needs to be supported, this might need more care though.

**Comment by davisagli** [comment]
In fact, this VoltoImageScalingFactory is registered with conditional zcml so that it is only used in Plone 5 (`zcml:condition="not-have plone-60"`)

So, I think an error from the missing method would only happen if you are using Plone 5 with the versions of plone.scale and plone.namedfile that are intended for Plone 6. Is that the case? It would be helpful to see the traceback to make sure we understand the error.

**Comment by cekk** [comment]
You're right as usually..we were testing new plone.scale and namedfile packages on a plone 52 (i didn't remembered it).
Without them, the error gone.

Here you are the traceback for reference:

```
2022-08-26 17:33:16,394 ERROR   [Zope.SiteErrorLog:35][waitress-1] AttributeError: http://localhost:7080/Plone/it/folder_listing
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 266, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 58, in __call__
  Module zope.pagetemplate.pagetemplate, line 133, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.utils, line 53, in raise_with_traceback
  Module chameleon.template, line 192, in render
  Module 95aab2872b4da1409a7c890b8e4437c3, line 1982, in render
  Module 608450dc8ea285d7bfbb3578b83a9ad8, line 860, in render_master
  Module 608450dc8ea285d7bfbb3578b83a9ad8, line 1489, in render_content
  Module 95aab2872b4da1409a7c890b8e4437c3, line 1967, in __fill_content_core
  Module 95aab2872b4da1409a7c890b8e4437c3, line 122, in render_content_core
  Module 95aab2872b4da1409a7c890b8e4437c3, line 493, in render_listing
  Module 95aab2872b4da1409a7c890b8e4437c3, line 903, in render_entries
  Module 95aab2872b4da1409a7c890b8e4437c3, line 1361, in render_listitem
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (image_scale.tag(item, 'image', scale=thumb_scale_list, css_class=img_class))
  Module <string>, line 1, in <module>
  Module plone.memoize.volatile, line 74, in replacement
  Module plone.namedfile.scaling, line 702, in tag
  Module plone.namedfile.scaling, line 613, in tag
  Module plone.namedfile.scaling, line 538, in scale
  Module plone.scale.storage, line 232, in pre_scale
AttributeError: 'VoltoImageScalingFactory' object has no attribute 'get_original_value
 - Expression: "python:image_scale.tag(item, 'image', scale=thumb_scale_list, css_class=img_class)"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 68: col 53)
 - Source:     ... python:image_scale.tag(item, 'image', scale=thumb_scale_list, css_class=img_class) ...
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "provider:plone.abovecontentbody"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 94: col 70)
 - Source:     ...
                                     ^
 - Expression: "context/@@main_template/macros/master"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 6: col 21)
 - Source:     ... tal:use-macro="context/@@main_template/macros/master"
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f0112340f70>
               options: {}
               args: ()
               nothing: None
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7f011f2bde80>
               request: <WSGIRequest, URL=http://localhost:7080/Plone/it/folder_listing>
               view: <Products.Five.browser.metaconfigure.SimpleViewClass from /opt/xxx/plone/eggs/plone.app.contenttypes-2.2.3-py3.8.egg/plone/app/contenttypes/browser/templates/listing.pt object at 0x7f01128b0070>
               context: <Container at /Plone/it>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f0111bd30d0>
               here: <Container at /Plone/it>
               container: <Container at /Plone/it>
               root: <Application at >
               traverse_subpath: []
               user: <SpecialUser 'Anonymous User'>
               default: <DEFAULT>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f01194d0b80>
               loop: {'item': <Products.PageTemplates.engine.RepeatItem object at 0x7f00f2f7c670>}
               target_language: None
               translate: <function BaseTemplate.render.<locals>.translate at 0x7f01196d6ca0>
               macroname: 'master'
               attrs: {}
```'

plone.namedfile = 6.0.0b2
plone.scale = 4.0.0b1

**Review by jensens — APPROVED** [review]

**Comment by sneridagh** [comment]
What's the status on this one? Can we merge? @cekk how about @mauritsvanrees suggestion?

**Comment by mamico** [comment]
@cekk @mauritsvanrees @sneridagh  
If I read well, customization was for handle svg (https://github.com/plone/plone.volto/commit/d403c63124b50aa45cce8a8f91d90efd34c83db3), but in plone.namedfile 5.6.0 svg are managed by plone.namedfile itself (https://github.com/plone/plone.namedfile/pull/104).

My proposal is to remove the `ImageScaleFactory` customization in plone.volto and fix `namedfile >= 5.6.0` in the package requirements.

**Comment by davisagli** [comment]
The same change was already done

**Pull request closed without merging**
