### PR TITLE
Code cleanup, add 'volto.blocks' behavior to Plone Site GS types info…

### PR DESCRIPTION
**Pull request by sneridagh**
…. Remove 'Collection' from types in GS. Remove 'plone.richtext' behavior from Plone Site, Document, News Item, Events.

### CODE REVIEW

**Comment by sneridagh** [comment]
@jensens @tisto meh, I added the blocks behavior to `Plone Site` and GS is complaining in 5.2 because it does not know about it :/ 

We could make 4.0.0 Plone 6 only. Wasn't that the idea? I can't remember now.

**Comment by tisto** [comment]
@sneridagh I would prefer to keep things working for both versions, if that is possible with reasonable effort. Maintaining multiple branches of multiple packages (plone.volto, plone.restapi, Volto) will not end up well, we saw this in the past (p.a.contenttypes & plone.app.event, plone.app.discussion & dexterity). Plone 5.2 won't go away anytime soon.

**Comment by tisto** [comment]
@sneridagh zcml condition won't work for gs. A separate profile for Plone 6 seems overkill but might be the only option. What if we register the behavior via Python code and make it conditional?

**Comment by sneridagh** [comment]
I agree, let's keep them compatible although it's ugly. It can be done programmatically, of course. I'll prepare it.

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
@sneridagh can you resolve the conflict? I guess this should go into the first 4.0.0a1 as well, right?

**Comment by sneridagh** [comment]
@tisto Yep

**Comment by sneridagh** [comment]
@tisto Done! Take a final look before merging.

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@sneridagh LGTM! Feel free to hit the merge button once Jenkins is happy.

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
