### PR TITLE
The collective.folderishtypes package will not be installed by default

### PR DESCRIPTION
**Pull request by ale-rt**
I am just experimenting :)
See https://github.com/plone/Plone/pull/20

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@plone/volto-team It seems removing collective.foldersih has no effect on the build.
I am quite puzzled :)

**Comment by tisto** [comment]
@ale-rt Volto can run without folderish types. It will adapt to the settings of the individual content types. If you don't install folderishtypes, you won't get them. Volto acceptance tests (that we don't run in this build) will fail for sure though.

**Comment by ale-rt** [comment]
@tisto how can I trigger the Volto acceptance tests to run with this PR?

**Comment by tisto** [comment]
@ale-rt create a PR on Volto that checks out your PR of plone.volto.

**Comment by ale-rt** [comment]
Thank you! I will try :)

**Comment by ale-rt** [comment]
@tisto It does not look like it is causing any issue https://github.com/plone/volto/pull/2892 :thinking:

**Comment by ale-rt** [comment]
Ah there is no auto-checkout... wait please

**Comment by sneridagh** [comment]
Superseded by: #36

**Pull request closed without merging**
