### PR TITLE
New field with huge vocabulary defined in the widget options

### PR DESCRIPTION
**Pull request by tiberiuichim**

### CODE REVIEW

**Comment by tisto** [comment]
@tiberiuichim @sneridagh changelog entry is missing. That's just a new feature, so safe to merge for the 3.x branch, right?

**Comment by sneridagh** [comment]
@tiberiuichim adding `.coresandbox ` to `configure.zcml is wrong... we only want that conditionally, on demand from an external thing.

**Comment by sneridagh** [comment]
@tisto I can take care, it would be nice for testing purposes.

**Comment by sneridagh** [comment]
@tiberiuichim doh, I did the change T_T haha I didn't remember it, so blame on me! I reverted it.

@tisto now it should be good to go, for 3 I guess is fine.

@jenkins-plone-org please run jobs

**Pull request merged**
