### PR TITLE
Add block types index to zcatalog

### PR DESCRIPTION
**Pull request by margaridasp**
Fixes https://github.com/plone/volto/issues/4778

Needs a bit more work on nested blocks.

Note: depends on https://github.com/plone/plone.restapi/pull/1648

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]

**Comment by wesleybl** [comment]
One thing that I find strange is that types of content that do not have blocks, such as images, are indexed by the parent content. If an image is inside a page that has a slate block, the slate key lists that image.

**Comment by davisagli** [comment]
> it would be great to have some documentation about it

@sneridagh Sorry, good point. I'll work on this.

> why did we not include a metadata field for this? We cannot ask a content brain for his blocks without getting the content and iterate over them.

I didn't anticipate a need for this. I don't think it would be needed unless we want to show what types of blocks an item uses in a listing, which seems unlikely.

> One thing that I find strange is that types of content that do not have blocks, such as images, are indexed by the parent content. If an image is inside a page that has a slate block, the slate key lists that image.

@wesleybl This is a bug! The indexer needs to do aq_base(obj).blocks instead of just obj.blocks. I was mistakenly thinking that the indexer decorator takes care of wrapping the context in an explicit acquisition wrapper.

**Pull request merged**
