### PR TITLE
Remove c.folderishtypes dependency.

### PR DESCRIPTION
**Pull request by sneridagh**
@ale-rt Done, migrated away from c.folderishtypes. 

Now we need now the migration script from `collective.folderishtypes.dx.content.x` to `plone.volto.content.x` of the existing content. Do you know an accepted and reliable way for doing this? Any pointer?

### CODE REVIEW

**Comment by ale-rt** [comment]
AFAIU what you need to do is just this: https://github.com/plone/plone.volto/pull/29 and document that if somebody wants to use volto with c.folderishtypes (maybe because he had them in the past) he will have to add it to the buildout.

**Comment by ericof** [comment]
@ale-rt, @sneridagh I do believe we need to make sure old pickled objects will not break, right? I do remember that in the past there was a way to say references to a class a.b.c should be resolved by d.e.f

**Comment by ale-rt** [comment]
> @ale-rt, @sneridagh I do believe we need to make sure old pickled objects will not break, right? I do remember that in the past there was a way to say references to a class a.b.c should be resolved by d.e.f

The way you are referring to is to use `from plone.app.upgrade.utils import alias_module`, which is widely used in `plone.app.upgrade`, see: https://github.com/plone/plone.app.upgrade/blob/9605da7fb462ec3849a85a870152500402eb6c43/plone/app/upgrade/__init__.py

But as far as I understand removing c.folderishtypes is much more (I am thinking about FTIs and other things that should be reset).
IMO the only sane way to have plone.volto in core and support the old installation is to cut a breaking release that does not depend anymore on c.folderishtypes.
I have no idea on how to make a proper upgrade of a volto DB, but the easiest thing to do is that existing sites will add c.folderishtypes to their sites. 

The same happened for years with archetypes. 

If you wanted to keep using AT you just needed to add archetypes to your buildout.

**Comment by jensens** [comment]
The problem is the abuse of base classes. Dexterity has this idea of two base classes and everything else is declarative by schema. For some reason someone thought its a good idea to create own base classes by FTI (this is so Archetypes!) and that is what we have in p.a.contenttypes. Ok, you now say, but I want it implement IDocument. Yes, I say, then apply a behavior (even if its an empty marker) and you got it. Well, that's OT, but that;s where  we are.

**Comment by sneridagh** [comment]
@jensens I get your point, but we are teaching this is the way to go: https://training.plone.org/5/mastering-plone/dexterity_2_talk.html#the-type-registration since ages. I think the reason behind is for being able to customize accessors/mutators and add class methods, right?

@ale-rt We need this anyways. We come from an "anomaly" created by necessity to get things done in a timely manner. So from my point of view, we need to normalize it now, by creating a migration step. Supporting both it's not an option (they will collide). Creating a 4.0.0 for the breaking change would be my preferred way to go. Then the migration.

/cc @tisto @ericof

**Comment by ericof** [comment]
@ale-rt That is it ```from plone.app.upgrade.utils import alias_module```, thanks.

The idea would be to have aliases from the old to the new (if someone does not have c.folderish.. anymore but has data in the ZODB)

Then the upgrade step will:

- Replace the fti's (That is already taken care of in this PR)
- Search for all Document, News Item and Event types, and migrate from the old base class to the new (and recatalog them)
- Uninstall c.folderish

Imho we cannot tell existing Volto users that they are on their own (or that they need to pin plone.volto < 4 to avoid problems)

**Comment by jensens** [comment]
> I think the reason behind is for being able to customize accessors/mutators and add class methods, right?

Yeah, I know, a shame. completely unnecessary given we have behaviors.

**Comment by jensens** [comment]
> Creating a 4.0.0 for the breaking change would be my preferred way to go. Then the migration.

+1 break it, but in the new major do check if c.folderishtypes is there and if yes fail on startup.

**Comment by tisto** [comment]
This will go into a plone.volto 4.0 for sure. Though, we need a working upgrade step and migration story. We just can not (and should not) support multiple versions of plone.volto over a longer period of time. We need to provide a proper upgrade step so that all existing Volto users can easily upgrade to plone.volto 4.0.

**Comment by ericof** [comment]
> +1 break it, but in the new major do check if c.folderishtypes is there and if yes fail on startup.
I'm not sure about breaking, as I do see the need for the upgrade step to uninstall it.

**Comment by ale-rt** [comment]
> This will go into a plone.volto 4.0 for sure. Though, we need a working upgrade step and migration story. We just can not (and should not) support multiple versions of plone.volto over a longer period of time. We need to provide a proper upgrade step so that all existing Volto users can easily upgrade to plone.volto 4.0.

I would start immediately by removing the installation of `collective.folderishtypes` by default.
That will avoid an unnecesary migration to the people who want to start using volto tomorrow.

**Comment by ale-rt** [comment]
> The idea would be to have aliases from the old to the new (if someone does not have c.folderish.. anymore but has data in the ZODB)
> 

I do not think this is a fully satisfactory solution... 
This can lead to unpredictable situations because you will have old content and new content that will be two different things starting from the fact that one will be folderish and the other not...

> Then the upgrade step will:
> 
> * Replace the fti's (That is already taken care of in this PR)
> * Search for all Document, News Item and Event types, and migrate from the old base class to the new (and recatalog them)
> * Uninstall c.folderish
> 

I am not sure. 
So far I see that the state you want to reach is more similar to the one described here: https://github.com/plone/volto/pull/2892#issuecomment-989210332

But:
- I never had a volto DB in my hands.
- you guys decide what to do here

> Imho we cannot tell existing Volto users that they are on their own (or that they need to pin plone.volto < 4 to avoid problems)

Well, they will need to install `collective.folderishtypes` until a migration strategy is well defined (hopefully soon).
It was the same with people using archetypes with Plone 5.2.

But has said, I can only report my feelings on that.
You developed volto, you are running projects on that and you decide what is best for you to trive :)

**Comment by mauritsvanrees** [comment]
Can someone remind me why we want to get rid of `collective.folderishtypes`? I began to get the idea that we did not want this because we do not want _any_ form of folderish types, and `plone.volto` or Volto itself would maybe be changed to work with the standard non-folderish types. But the folderish types are being reassembled in this PR, so that is apparently not the problem.

Is there too much old code or too many broken ideas in `collective.folderishtypes`? Sure, a fresh, clean start is nice, and less packages is nice. But isn't it easier to cleanup the old package, throw out Archetypes code and make a breaking release?

I don't know if that helps and if it is easier than what you are doing here. It would avoid a migration, so that's a start.

I don't have an opinion here. Just wondering. :-)

**Comment by ericof** [comment]
> I do not think this is a fully satisfactory solution... This can lead to unpredictable situations because you will have old content and new content that will be two different things starting from the fact that one will be folderish and the other not...

So, all Volto projects use c.folderish, and this PR is simply moving the code from c.folderish here. We are not talking about old plone.app.contenttypes News Item being "changed" into Folderish, but simply moving the location of the class that builds the content/


> Well, they will need to install `collective.folderishtypes` until a migration strategy is well defined (hopefully soon). It was the same with people using archetypes with Plone 5.2.

I think (and I could be wrong, of course) this is not an Archetypes to Dexterity situation -- when we had two very distinct codebases that really need a migration, but more of a base class that moved from one package to the other.

The migration here needs to make sure c.folderis classes are moved to plone.volto classes.

> But has said, I can only report my feelings on that. You developed volto, you are running projects on that and you decide what is best for you to strive :)

I do believe this is an important discussion, because it could shape the way we deal with migrations and upgrades in the years to come :-)

**Comment by ericof** [comment]
> Is there too much old code or too many broken ideas in `collective.folderishtypes`? Sure, a fresh, clean start is nice, and less packages is nice. But isn't it easier to cleanup the old package, throw out Archetypes code and make a breaking release?

imo, cleaning up c.folderishtypes (removing AT, adding proper tests), and then maintaining it is a bad solution in the long run, and we should make the cut now, before Plone 6.0 is shipped (otherwise, it will stay forever :-D)

**Comment by jensens** [comment]
Isn't it a better idea to move c.folderishtypes to p.a.contenttypes as an alternative profile? Just said, we use often folderish types in classic too. OTOH it is that incredibly simple, I always build some FTIs and done. As said, these base classes are always pimples on my otherwise clean code base ;).

**Comment by sneridagh** [comment]
@fredvd @pbauer Since you both have lots of experience with in-place migrations, could you weigh in?

The idea was always to remove c.folderishtypes, then migrate the content in-place to use the new classes. Did you have experience with such a use case?

@jensens if we start to spread the Volto specific things across all the code base, the testing environment and the dependencies KGS would get crazy quickly (now it's starting to be). So I would maintain it close to plone.volto package. Same when we decide to move the behaviours and indexers still in p.restapi. Regarding the base classes, I have no strong opinion...

**Comment by jensens** [comment]
> if we start to spread the Volto specific things across all the code base,

Well, IMO this is a classical case for a PLIP. It is backend related, it spans several fields of interest (no, folderish types is not volto only). And it needs a wise broad decision.

**Comment by tisto** [comment]
@mauritsvanrees the arguments to get rid of c.folderishtypes are (just summarizing here what ppl said):

- it is a collective package, so we can not depend on it in core (not sure how valid that is)
- the package still has AT dependencies (optional)
- it is not worth the effort to maintain a package that requires a few lines of code in plone.volto

@jensens the @plone/framework-team discussed this matter in-depth and made the following decisions (I don't have time to look up the notes right now):

- Plone Classic will not ship with folderish types (it is too intrusive, too risky and not worth the effort), it should go into plone.volto
- we should get rid of the c.folderishtypes dependency before Plone 6 (because of the arguments listed above)

TBH I don't have a super-strong opinion either way. We could keep c.folderishtypes (though, I tend to get rid of it) and we could make stuff folderish everywhere (it would need a PLIP a champion and ppl who are willing to put a considerable amount of effort into Plone Classic).

Though, I would like to second @sneridagh argument that we have to be super careful not to spread functionality across packages. We are in a transition period where we have to keep stuff together to not end up with endless KGS settings. We just can not manage this as the "release team".

**Comment by ale-rt** [comment]
I confirm what @tisto said about the decision to not have folderish types (https://community.plone.org/t/fwt-meeting-minutes-2021-09-21/14362).

**Comment by ericof** [comment]
I've added migration and aliases (as suggested by @ale-rt) to this PR.
Also, I tested it locally using a Data.fs with <500 content items to be migrated, following these steps:

1. Buildout with a released plone.volto version, create 500 contents
2. Add the branch of this PR as develop, re-run buildout and make sure c.folderishtypes is not available
3. Start the instance and check that all content is still accessible (thanks to the aliases)
4. Run the upgrade step of plone.volto
5. Check the content is still accessible and the interfaces were fixed on the catalog
6. Stop the instance, remove the aliases from patches.py
7. Start the instance and the contents are still accesssible

**Review by jensens — APPROVED** [review]
Thanks for answering my nasty questions ;) LGTM

**Comment by sneridagh** [comment]
@ericof just tried it out in our client project default content, and it works like a charm.
However, I experienced some glitches, when removing the aliases. Namely:

Seen in the console:

```
2021-12-11 16:57:11,842 WARNING [OFS.Uninstalled:82][waitress-1] Could not import class 'FolderishDocument' from module 'collective.folderishtypes.dx.content'
```

and alike (although the content showed up)

This one is a bit more worry-ful:

```
2021-12-11 17:00:36,977 ERROR   [Zope.SiteErrorLog:35][waitress-1] AttributeError: http://localhost:3000/de/pgi/pgi-7/leistungen/@navigation
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 161, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 374, in publish_module
  Module ZPublisher.WSGIPublisher, line 264, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.rest.service, line 22, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.navigation.get, line 194, in reply
  Module plone.restapi.services.navigation.get, line 40, in __call__
  Module plone.restapi.services.navigation.get, line 177, in build_tree
  Module plone.memoize.view, line 59, in memogetter
  Module plone.restapi.services.navigation.get, line 127, in navtree
  Module collective.solr.monkey, line 23, in searchResults
  Module collective.solr.dispatcher, line 45, in __call__
  Module Products.CMFPlone.CatalogTool, line 463, in searchResults
  Module Products.ZCatalog.ZCatalog, line 627, in searchResults
  Module Products.ZCatalog.Catalog, line 1094, in searchResults
  Module Products.ZCatalog.Catalog, line 705, in search
  Module Products.ZCatalog.Catalog, line 1010, in sortResults
  Module Products.ZCatalog.Catalog, line 781, in _sort_iterate_resultset
  Module plone.folder.nogopip, line 101, in documentToKeyMap
  Module plone.folder.nogopip, line 27, in traverse
  Module plone.folder.ordered, line 230, in __getitem__
  Module plone.folder.ordered, line 71, in _getOb
  Module Products.BTreeFolder2.BTreeFolder2, line 220, in _getOb
AttributeError: 'FolderishDocument' object has no attribute '__of__'
```

Since the object threw a 404... 

The problems went all away when I brought the alias back.

**Comment by ericof** [comment]
@sneridagh After running the migration?

**Comment by sneridagh** [comment]
@ericof yes, following all the steps in your list.

**Comment by ericof** [comment]
@sneridagh Strange (as I've used the same dataset). I will try that again and see what did I miss

**Comment by sneridagh** [comment]
@ericof the catalog and everything else looked good (I haven't deep inspected via Python console the content items though).

**Comment by jensens** [comment]
Hint: there's a known problem when references are in place. The original object is migrated, but a reference can have a ghosted object with the old class. If the reference is accessed the object gets the old class back due to some magic. I am not 100% sure who told me about this, IIRC @pbauer or @ale-rt (but I may be wrong).

**Comment by ericof** [comment]
Damn, I saw that somewhere as well, but forgot to test for it.

**Comment by fredvd** [comment]
I think I mentionned this on Discord 1-2 days ago.  Manuel Rheinhardt from Syslab did a talk about these issues at the PloneTagung 2019.  I e-mailed him personally 2 hours ago to ask if he still has his sheets available from that talk. 

https://plonetagung.de/2019/talks/persistence-is-futile

**Comment by mauritsvanrees** [comment]
I saw a problem with relations last month in a project that we took over for maintenance. It was Plone 4.3.4, moved it to 4.3.20 as start. It was using Grok for the content class used on the homepage, and one interface lingered. At first I got rid of it with `bin/zodbupdate` using a dict rename from `grokcore.component.interfaces IContext` to `zope.interface Interface`. Should have the same effect as an alias like we are doing here. Result was that I could no longer edit the homepage, and got a traceback:

```
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.z3cform.layout, line 66, in __call__
      Module plone.z3cform.layout, line 50, in update
      Module plone.dexterity.browser.edit, line 64, in update
      Module plone.z3cform.fieldsets.extensible, line 59, in update
      Module plone.z3cform.patch, line 30, in GroupForm_update
      Module z3c.form.group, line 145, in update
      Module plone.app.z3cform.csrf, line 21, in execute
      Module z3c.form.action, line 98, in execute
      Module z3c.form.button, line 315, in __call__
      Module z3c.form.button, line 170, in __call__
      Module plone.dexterity.browser.edit, line 28, in handleApply
      Module z3c.form.group, line 126, in applyChanges
      Module zope.event, line 31, in notify
      Module zope.component.event, line 24, in dispatch
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module zope.component.event, line 32, in objectEventNotify
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module z3c.relationfield.event, line 76, in updateRelations
      Module zc.relation.catalog, line 546, in unindex
      Module zc.relation.catalog, line 556, in unindex_doc
      Module zc.relation.catalog, line 621, in _remove
    KeyError: <class 'zope.interface.Interface'>
```

So the relation machinery has a broken class left, either the `to_object` or `from_object` of a RelationValue. I put back the original copy of the database where I did not run `bin/zobupdate`. Got the same traceback, except the KeyError was now:

```
    KeyError: <class 'grokcore.component.interfaces.IContext'>
```

Workaround for me: forget about the rename dict, and re-add `grokcore.component` to the eggs, then it keeps working for now. Might have been Plone 4 specific.

One possible solution can be to repopulate the BTrees of the IntIds utility. I found that necessary in different project (Plone 5.2, Python 3), where zexps had been imported twice. See [`fix_intids` script](https://github.com/zestsoftware/plonescripts/blob/master/fix_intids.py) which does the following and a lot more:

```
intid_refs = list(intids.refs.items())
intids.ids.clear()
intids.refs.clear()
for key, value in intid_refs:
    intids.refs[key] = value
    intids.ids[value] = key
```

I have seen that this may be needed anyway, because the hash function of BTrees may have changed, though I guess this is more likely when going from Python 2 to 3.

Two more thoughts:

- The previous classes can linger in the CMFEditions history.
- Previous class can linger until you do a zeopack.

**Comment by ale-rt** [comment]
If you want to rebuild the relations you can use https://github.com/collective/collective.relationhelpers, this is the easiest way.

Anyway this might not solve all your problems because you will also have references of the old class in the history storage.
If you want to get rid of all the problems you should run `zodbupdate` (like if you would need to migrate to Python3, this documentation will apply perfectly https://docs.plone.org/manage/upgrading/version_specific_migration/upgrade_zodb_to_python3.html).

Also if you want to be sure your DB is fine, run `zodbverify`.

**Comment by ale-rt** [comment]
> Hint: there's a known problem when references are in place. The original object is migrated, but a reference can have a ghosted object with the old class. If the reference is accessed the object gets the old class back due to some magic. I am not 100% sure who told me about this, IIRC @pbauer or @ale-rt (but I may be wrong).

It might have been me. 
That happens if you switch the `__class__` in the persistent object and you have some relations in place. 
There are chances that you wake up the relation first (whose instance `__class__` is still the old one) and then your zope client is convinced your object is an instance of that class until you restart it and get the object from the ZEO server with the proper one.
At least this is what I remember/understood about that.

I think this was one of the topics covered by @reinhardt talk in Plone tagung.
This is solved when you run `zodbupdate` providing a proper alias (because all the references are migrated in the same way).

**Comment by tiberiuichim** [comment]
Can this be done with an offline migration script? Load data for all oids, check their class, change it?

**Comment by jensens** [comment]
> Can this be done with an offline migration script? Load data for all oids, check their class, change it?

This is what zodbupdate do, run low level over all oids with its pickle and work on it.

**Comment by reinhardt** [comment]
FTR, [here are my slides from the Plone Tagung talk](https://reinhardt.github.io/zodbtalk/slides.html#1). I think you're on the right track with zodbupdate.

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

For me this is good to merge.

I would like to make a Plone 6 alpha 3 soon, before the end of the work week. If we have a release of plone.volto with this, it could be included. A new plone.rest release and yet another plone.restapi release are welcome too. But don't hasten it, it can always be added in a fourth alpha.

**Pull request merged**
