### PR TITLE
Fix unchecked checkboxes in migrate_to_volto

### LINKED ISSUE #124: Inconsistent Behavior When Unchecking Checkboxes in migrate_to_volto form
When the checkboxes for migrating to Volto are unchecked, their values are set to None. As a result, the following statements are always evaluated as True, causing the migration of folders, default pages, and the purging of rich text always occur.

https://github.com/plone/plone.volto/blob/7c0ba3336907288895c52028b7a87ffea81d06cc/src/plone/volto/browser/migrate_to_volto.py#L40-L42

### PR DESCRIPTION
**Pull request by pbauer**
Fix #124

### CODE REVIEW

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@pbauer Wouldn't it make more sense to change the default values on the server side at https://github.com/plone/plone.volto/blob/7c0ba3336907288895c52028b7a87ffea81d06cc/src/plone/volto/browser/migrate_to_volto.py#L40-L42 ?

**Comment by pbauer** [comment]
> @pbauer Wouldn't it make more sense to change the default values on the server side at
> 
> https://github.com/plone/plone.volto/blob/7c0ba3336907288895c52028b7a87ffea81d06cc/src/plone/volto/browser/migrate_to_volto.py#L40-L42
> ?

Done. I would still keep the additional checkboxes to make them fully actually functional when kept unchecked. I was unaware that If a checkbox is unchecked when its form is submitted, neither the name nor the value is submitted to the server. It was actually the first time that hit me :)

**Comment by davisagli** [comment]
> I was unaware that If a checkbox is unchecked when its form is submitted, neither the name nor the value is submitted to the server. It was actually the first time that hit me :)

Right, now I remember this. But it is still okay for no value to be sent, as long as the server side does not default to True in that case.

Mm, looks like the tests fail now.

**Comment by davisagli** [comment]
@pbauer The change to the tests made me realize that we changed the default state of the checkboxes, which was not the original intent here. Sorry that I was confused and asked for additional work. I think we should reset the branch to this commit (before my first review) and merge it: https://github.com/plone/plone.volto/pull/125/commits/c93f85ffe5b2244cc02965b13e754ee62fb2676b

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — APPROVED** [review]

**Pull request merged**
